# General rule
windowrule {
    name = sidebar general
    match:initial_class = sidebar.*

    border_size = 2
    float = on
    no_anim = on
    opacity = 1.0 0.4 1.0
    rounding = 0
    size = (monitor_w*0.33) (monitor_h-4)
}
# Window Positioning Rules
windowrule = match:initial_class sidebar.left, move 0 2
windowrule = match:initial_class sidebar.right, move (monitor_w*0.66) 2

bind = SUPER, Bracketright, exec, ~/.config/hypr/toggle-sidebar right
bind = SUPER, Bracketleft, exec, ~/.config/hypr/toggle-sidebar left
