# Window Rendering Rules
windowrule = match:class sidebar.*, float on
windowrule = match:class sidebar.*, size 33% 100%
windowrule = match:class sidebar.*, opacity 1.0 0.4 1.0
windowrule = match:class sidebar.*, border_size 2
windowrule = match:class sidebar.*, rounding 0
windowrule = match:class sidebar.*, no_anim on

bind = SUPER, Bracketright, exec, ~/.config/hypr/toggle-sidebar right
bind = SUPER, Bracketleft, exec, ~/.config/hypr/toggle-sidebar left
