monitor=,preferred,auto,auto

# Launch the all the hooks
exec-once = ~/.config/wayland/rc.sh

# XDG environment variables
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_rules =

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
    follow_mouse = 2
    mouse_refocus = false
    float_switch_override_focus = 0
}

general {
    gaps_in = 20
    gaps_out = 2,40,40,40
    border_size = 8
    col.active_border = rgba(33ccff75)
    col.inactive_border = rgba(59595955)

    layout = master

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

cursor {
    no_warps = true
}

layerrule = blur on, match:namespace rofi

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 6
    dim_inactive = true
    dim_strength = 0.05

    blur {
        enabled = true
        size = 5
        passes = 2
    }

    shadow {
        enabled = false
    }
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_on_top = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
}

misc {
    force_default_wallpaper = 0
    exit_window_retains_fullscreen = 1
    mouse_move_focuses_monitor = false
    vfr = true
    focus_on_activate = true
}

debug {
    disable_logs = true
}

xwayland {
    force_zero_scaling = true
}

ecosystem {
    no_update_news = true
}

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = match:class *, suppress_event maximize # You'll probably like this.
# Workspace auto routing
windowrule = match:class firefox, workspace web
windowrule = match:class org.qutebrowser.qutebrowers, workspace web
windowrule = match:class WebCord, workspace chat
windowrule = match:class obsidian, workspace notes
windowrule = match:class org.prismlaunch.PrismLauncher, workspace games
# Fix terminal opacity dimming (terminals are the only one I really care about dimming inactive)
windowrule = match:class org.wezfurlog.wezterm, opacity 1.0 0.8 1.0
# Grab focus on pinentry since it's probably a warranted focus grab
windowrule = match:class pinentry-*, stay_focused on
# Give xwayland windows a purplish border
windowrule = match:xwayland on, border_color rgba(8866ff75)
# This is a weird one, webcord popups are actually un-classed floating windows and get blurred
windowrule = match:xwayland on, match:class "", match:float on, no_blur on
# xwaylandbridge settings, source: https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/#xwayland
windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

source=~/.config/hypr/hyprland.d/*.conf
