#!/usr/bin/env bash

set -euo pipefail

if [[ -z "$@" ]]; then
    exec python3 -m cfgtools \
        "systems.$(cat /proc/sys/kernel/hostname | awk '{print tolower($0)}')"
else
    exec python3 -m cfgtools "$@"
fi
