#!/usr/bin/env bash

set -euo pipefail

if [[ -z "$@" ]]; then
    exec python3 -m cfgtools \
        "systems.$(cat /proc/sys/kernel/hostname | awk '{print tolower($0)}')"
else
    # the two seds are for:
    #  1. convert /'s into .'s so the fs completion translates into python imports
    #  2. trim trailing .'s from fs completion appending a trailing / for dirs
    exec python3 -m cfgtools "$(echo $@ | sed "s#/#.#g" | sed "s#\.\$##")"
fi
