#!/usr/bin/env bash

set -euo pipefail

PASSWORD_LENGTH=24
export PASSWORD_STORE_DIR=${PASSWORD_STORE_DIR:-$HOME/.local/password_store}

fail() {  # output failure message and fail
    echo ${1:-'Something went wrong.'}
    exit ${2:-1}
}
debug() {
    echo ${1:-} >&2
}
message() {  # dump a message to the rofi message bar
    echo -en "\0message\x1f$1\n"
}

list() {  # dump list of stored passwords with standard prefix
    find $PASSWORD_STORE_DIR -name "*.gpg" -printf "%P\n" \
        | sed "s/.gpg//"
}

create() {  # populate a new password
    local password=${1:-}
    [[ -z "$password" ]] && fail 'No password to generate'
    pass generate $password $PASSWORD_LENGTH
}

get() {  # retrieve the stored password as passed in
    local target=${1:-}
    [ -z "$target" ] && fail 'Need a password to retrieve' 7
    local output=${2:-xclip}
    # Lazy attempt at differentiating x and wayland
    if which xclip &>/dev/null; then
        local is_xorg=1
    else
        local is_xorg=
    fi

    # temporarily populate the clipboard with the value
    if [[ "$output" == "xclip" ]]; then
        if [[ ! -z $is_xorg ]]; then
            local prvs=$(xclip -selection 'clipboard' -out)
        else
            local prvs=$(wc-paste)
        fi
        coproc (
            # generates the password and redirects into the clipboard
            if [[ ! -z $is_xorg ]]; then
                pass show "$target" 2>/dev/null \
                    | head -n1 | xclip -in -selection 'clipboard'
            else
                pass show "$target" 2>/dev/null \
                    | head -n1 | wl-copy
            fi
            # after 30 seconds, restore to the old contentsb  b
            sleep 30
            if [[ ! -z $is_xorg ]]; then
                echo "$prvs" | xclip -in -selection 'clipboard'
            else
                echo "$prvs" | wl-copy
            fi
        )
    elif [[ "$output" == "xdotool" ]]; then
        coproc (
            # use a 0 second sleep to background this to allow rofi to close
            sleep 0
            # outputs the password into the active window
            if [[ ! -z $is_xorg ]]; then
                xdotool type --clearmodifiers --window $(
                    xdotool getactivewindow
                ) --delay 5 $(
                    pass show "$target" 2>/dev/null \
                        | head -n1
                )
            else
                wtype -d 5 $(pass show "$target" 2> /dev/null | head -n1)
            fi
        )
    else
        exit 6
    fi
}

ACTION="${1:-}"
if [[ -z "$ACTION" ]]; then
    echo -en "\0use-hot-keys\x1ftrue\n"
    list
elif [[ "$ACTION" == "oops" ]]; then
    exit 5
else
    message "Got action: $ACTION"
    if ! list | grep "^$ACTION$" >/dev/null; then
        create $ACTION
    fi

    if [[ "$ROFI_RETV" == "10" ]]; then
        handler="xclip"
    else
        handler="xdotool"
    fi

    get $(echo $ACTION | cut -d' ' -f2-) ${handler:-}
fi
