#!/usr/bin/env bash

set -euo pipefail

SYSTEM_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/system"
if [[ -e $SYSTEM_FILE ]]; then
    source $SYSTEM_FILE
else
    # Sane defaults that *should* be defined per system, but we still want to set if
    #  there is no system specific definitions...
    bspc monitor -d term web code chat
fi

# looks
POLYBAR_HEIGHT=24
PADDING=24
bspc config border_width         1
bspc config window_gap          48
bspc config bottom_padding      $PADDING
bspc config top_padding         $(($PADDING + $POLYBAR_HEIGHT))
bspc config left_padding        $PADDING
bspc config right_padding       $PADDING

# layout controls
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# output change handling
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# rules
set_rules() {
    if ! bspc query --desktops --names | grep $1 &>/dev/null; then
        echo "No desktop defined for $1, skipping..."
        return
    fi

    desktop=$1
    shift
    while (( $# )); do
        bspc rule -a "$1" desktop=$desktop focus=on follow=on
        shift
    done
}

set_rules 'web' \
    'Chromium' 'Google-chrome' 'firefox' 'qutebrowser'
set_rules 'games' \
    'Lutris' 'MultiMC5' 'Steam'
set_rules 'video' \
    'mpv' 'streamlink-twitch-gui'
set_rules 'chat' \
    'Discord' 'discord' 'android-messages-desktop' 'TelegramDesktop'

# Floating by default
for c in 'Peek' 'scrcpy' 'pinentry-qt'; do
    bspc rule -a "$c" state=floating focus=on
done
# Fixes

# Zathura wants to float by default, not desirable
bspc rule -a "Zathura" state=tiled

EXTERNAL_RULES_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/external_rules"
if [[ -x $EXTERNAL_RULES_FILE ]]; then
    bspc config external_rules_command $EXTERNAL_RULES_FILE
fi

systemctl --user start statusbar.service
