$builtin_monitor = desc:Sharp Corporation 0x14F9
monitor = $builtin_monitor, preferred, 0x0, 1

$dock_monitor = desc:ASUSTek COMPUTER INC PA278QV M4LMQS061475
monitor = $dock_monitor, preferred, 0x0, 1, mirror, $builtin_monitor
#monitor = $dock_monitor, disable

input {
    touchpad {
        disable_while_typing = true
    }
}

# Mod + arrow keys to slide between workspaces
bind = $mainMod, left, workspace, r-1
bind = $mainMod, right, workspace, r+1

workspace = 1, defaultName:term,  persistent:true, monitor:$builtin_monitor
workspace = 2, defaultName:web,   persistent:true, monitor:$builtin_monitor
workspace = 3, defaultName:notes, monitor:$builtin_monitor
workspace = 4, defaultName:chat,  monitor:$builtin_monitor
workspace = 5, defaultName:video, monitor:$builtin_monitor

exec-once=hyprctl --batch "dispatch workspace 1; dispatch workspace 2; dispatch workspace 1"

# Rules
windowrule = match:class org.qutebrowser.qutebrowser, workspace 2
windowrule = match:class obsidian, workspace 3
windowrule = match:class WebCord, workspace 4
windowrule = match:class mpv, workspace 5
