[global]
username_cmd = "jq -r .username ~/.cache/spotifyd/zeroconf/credentials.json"
use_mpris = true
device_type = "computer"
device = "pipewire"
volume_controller = "none"
initial_volume = "70"
autoplay = false
disable_discovery = true
