# All in seconds
SECONDS_TO_SCREENLOCK=480  # Idle time until the screen locks
SECONDS_TO_DIMMER=360  # Idle time until dimmer starts
## NOTE: the value XSECURELOCK_DIM_TIME_MS should be equal to
#   SECONDS_TO_SCREENLOCK - SECONDS_TO_DIMMER * 100
if which xset &>/dev/null; then
    xset s on \
     && xset s \
        $SECONDS_TO_DIMMER \
        $(( $SECONDS_TO_SCREENLOCK - $SECONDS_TO_DIMMER ))
fi

# vim: ft=bash
