layerrule = match:namespace ignis.notifications.*, blur on, ignore_alpha 0
layerrule = match:namespace ignis.bar.*, blur on, ignore_alpha 0
layerrule = match:namespace ignis.osd.*, blur on, ignore_alpha 0
layerrule = match:namespace ignis.popup, blur on, ignore_alpha 0
layerrule = match:namespace ignis.sidebar, blur on, ignore_alpha 0
