layerrule = match:namespace ignis.notifications.*, blur on
layerrule = match:namespace ignis.notifications.*, ignore_alpha 0
layerrule = match:namespace ignis.bar.*, blur on
layerrule = match:namespace ignis.bar.*, ignore_alpha 0
layerrule = match:namespace ignis.osd.*, blur on
layerrule = match:namespace ignis.osd.*, ignore_alpha 0
