if which gpg-agent&>/dev/null && gpg-connect-agent --quiet /bye &>/dev/null; then
  export GPG_TTY=$(tty)
  gpg-connect-agent updatestartuptty /bye &>/dev/null
  systemctl --user import-environment GPG_TTY
  systemctl --user import-environment GNUPGHOME
fi

# vim: ft=bash
