#!/usr/bin/env bash

set -euo pipefail

BUILD_DIR=${BUILD_DIR:-/build}
SHARE_DIR=${SHARE_DIR:-/src}

OUT=${OUT:-/pkgs}
# update packages to avoid weird issues with version mismatches
sudo pacman -Syu --noconfirm ${PKGS:-}

build_remote() {
   cd $BUILD_DIR
   local pkg=$1

   echo "Building AUR pkg: $pkg..."
   git clone "https://aur.archlinux.org/$pkg.git"

   cd $pkg
   makepkg --noconfirm --syncdeps --install --nocheck

   ls *.pkg.tar.xz &>/dev/null && cp *.pkg.tar.xz $OUT/
   ls *.pkg.tar.zst &>/dev/null && cp *.pkg.tar.zst $OUT/
}

build_local() {
   local tgt=$1
   local dst=$BUILD_DIR/$tgt

   echo "Building local pkg: $tgt..."
   mkdir -p $dst

   if [[ -d "$SHARE_DIR/$tgt" ]]; then
      cp -R "$SHARE_DIR/$tgt"/* $dst/
   else
      cp "$SHARE_DIR/$tgt" $dst/PKGBUILD
   fi

   cd $dst
   makepkg --noconfirm --syncdeps --install --nocheck

   ls *.pkg.tar.xz &>/dev/null && cp *.pkg.tar.xz $OUT/
   ls *.pkg.tar.zst &>/dev/null && cp *.pkg.tar.zst $OUT/
}

for pkg in "$@"; do
   if [[ -e "$SHARE_DIR/$pkg" ]]; then
      build_local $pkg
   else
      build_remote $pkg
   fi
done
