#!/usr/bin/env bash

set -euo pipefail

BUILD_DIR=${BUILD_DIR:-/build}
SHARE_DIR=${SHARE_DIR:-/src}
interactive=0

OUT=${OUT:-/pkgs}
# update packages to avoid weird issues with version mismatches
sudo pacman -Syu --noconfirm ${PKGS:-}

interactive_fixer() {
   echo ""
   echo "Opening shell so that you may fix the cause of the above build failure"
   echo "'exit' the shell once fixed and it will attempt to continue building."
   bash
}

build_remote() {
   cd $BUILD_DIR
   local pkg=$1

   if [[ -d "$BUILD_DIR/$pkg" ]]; then
      echo "Updating AUR pkg: $pkg..."
      cd $pkg
      git pull
   else
      echo "Building AUR pkg: $pkg..."
      git clone "https://aur.archlinux.org/$pkg.git"
      cd $pkg
   fi

   if ! makepkg --noconfirm --syncdeps --install --nocheck; then
      interactive_fixer
      makepkg --noconfirm --syncdeps --install --nocheck
   fi

   ls *.pkg.tar.xz &>/dev/null && cp *.pkg.tar.xz $OUT/
   ls *.pkg.tar.zst &>/dev/null && cp *.pkg.tar.zst $OUT/
}

build_local() {
   local tgt=$1
   local dst=$BUILD_DIR/$tgt

   echo "Building local pkg: $tgt..."
   mkdir -p $dst

   if [[ -d "$SHARE_DIR/$tgt" ]]; then
      cp -R "$SHARE_DIR/$tgt"/* $dst/
   else
      cp "$SHARE_DIR/$tgt" $dst/PKGBUILD
   fi

   cd $dst
   if ! makepkg --noconfirm --syncdeps --install --nocheck; then
      interactive_fixer
      makepkg --noconfirm --syncdeps --install --nocheck
   fi

   ls *.pkg.tar.xz &>/dev/null && cp *.pkg.tar.xz $OUT/
   ls *.pkg.tar.zst &>/dev/null && cp *.pkg.tar.zst $OUT/
}

for pkg in "$@"; do
   if [[ "$pkg" == "--interactive" ]]; then
      interactive=1
   elif [[ -e "$SHARE_DIR/$pkg" ]]; then
      build_local $pkg
   else
      build_remote $pkg
   fi
done

if [[ "$#" == "0" ]]; then
   exec bash
fi
