zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename $HOME'/.zshrc'

autoload -U compinit && compinit
autoload -U colors && colors
autoload -U vcs_info && vcs_info

zmodload zsh/complist
zmodload zsh/terminfo

DEBUG=${DEBUG:-0}

for r in $HOME/.local/environment/*; do
   [[ $DEBUG > 0 ]] && echo "zsh: sourcing $r"
   source $r
done # }}}

# Plugin/Settings configs
PLUGIN_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/plugins
[[ ! -d "$PLUGIN_DIR" ]] && mkdir -p "$PLUGIN_DIR"
ZSH_SETTINGS_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/settings
ZSHRC=$HOME/.zshrc

# Shell options
setopt nobeep
setopt correct
setopt prompt_subst

# Load settings {{{
for r in $ZSH_SETTINGS_DIR/*.zsh; do
   [[ $DEBUG > 0 ]] && echo "zsh: sourcing $r"
   source $r
done # }}}
# set shell colors {{{
if [ -f ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/colors ]; then
   . ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/colors
fi # }}}

# set initial title using TTY, only if interactive
if [[ -o interactive ]]; then
   which settitle &>/dev/null && settitle || /bin/true
   which term_info &>/dev/null && term_info || /bin/true
fi

# vim: ft=zsh foldmethod=marker
