layerrule = match:namespace ags.popup.*, blur on
layerrule = match:namespace ags.popup.*, ignore_alpha 0
layerrule = match:namespace ags.notifications, blur on
layerrule = match:namespace ags.notifications, ignore_alpha 0
layerrule = match:namespace ags.bar.*, blur on
layerrule = match:namespace ags.bar.*, ignore_alpha 0
layerrule = match:namespace ags.sidebar, blur on
layerrule = match:namespace ags.sidebar, ignore_alpha 0
layerrule = match:namespace ags.*, no_anim on
